baseURL = "http://luke-cd-website.s3-website-us-east-2.amazonaws.com"
languageCode = "en-us"
title = "Luke's Hugo Site via AWS Cloud9"
theme = "ananke"

[[deployment.targets]]
# An abritrary name for this target.
name = "awsbucket"
URL = "s3://luke-cd-website/?region=us-east-2"